### ISSUE TITLE
Logs

### ISSUE THREAD

**Issue by rishvidh** [rdeepak2002/reddit-place-script-2022#15]
Would it be possible for the log to say which pixel it just changed in (x,y) format?

Also does the script automatically look for the next changeable tile if the one it starts with is already the right color? And how does the R_START and C_START work? is the 0,0 top left or center and when using multiple accounts, how can you configure so that you get maximum coverage?

**Comment by rdeepak2002** [comment]
Hello, on line 71 of main.py I log the following:

```python
print("placing pixel with color index " + str(color_index_in) + " at " + str((x, y)))
```

At the moment, the script does not check whether the current pixel already has the correct color. There was an earlier issue pulled up regarding this and someone fixed it on their branch. Feel free to make a pull request to integrate this change since it would definitely be useful! 

ENV_R_START (x) and ENV_C_START (y) is the coordinate position for where the script will start drawing from the input image.jpg file. I added this because someone could do a setup where they have one account drawing starting from the top left of the image (0, 0) while another account could be drawing from the middle of the image (0, 50, assuming the image is 100 pixels tall). If they are both set to 0, then drawing will start from the top left of the image (aka the entire image will be drawn in that thread).

**Comment by rishvidh** [comment]
then say if I start with 0,50 what would the next pixel be? would it be 0,51 or 1,50 and also what happens when it's at the end of the line? say if goes from 0,50 to 0,100 what is the next pixel now?

**Comment by JAKONL** [comment]
I believe the screen shot below provides an example of how to configure the `.env` file with two user accounts where the first user account starts on row 0 and the second account starts on row 13. 

The latest version of the script increments the row until reaching the last pixel in the current row before proceeding to the next row at the first pixel.

![ExampleENV](https://user-images.githubusercontent.com/16417680/161360899-2c303f44-dfb1-4bf1-91e5-d162b28b249e.png)

**Comment by rdeepak2002** [comment]
The next pixel will be (1, 50), then (2, 50), then (3, 50), etc. Once the height limit is reached (i.e. the entire image has been drawn or the worker is done drawing its part of the image), it will restart from where it started and redraw the image (since previous people could have overridden the pixels you drew).

**Comment by rishvidh** [comment]
is there a way to make this increment horizontal? so 0,50 then 0,51 then 0,52 and so on? is that a simple change or is it more complicated?

**Comment by rdeepak2002** [comment]
Hello, I believe that (0,50), (0,51), then (0,52) would be vertical. Since we are starting at y position 50, then moving down to y position 51, then down to y position 52, etc.

**Comment by rdeepak2002** [comment]
But if you would like to change it to render the image in the vertical direction, you would have to modify the following code:

```python
current_r += 1

# go back to first column when reached end of a row while drawing
if current_r >= image_width:
    current_r = 0
    current_c += 1

# exit when all pixels drawn
if current_c >= image_height:
    print("__________________")
    print("Thread #" + str(credentials_index))
    print("done drawing image to r/place")
    print("__________________")
    break
```

I think a possible solution would be the following:

```python
current_c += 1

# go back to first column when reached end of a row while drawing
if current_c >= image_height:
    current_c = 0
    current_r += 1

# exit when all pixels drawn
if current_r >= image_width:
    print("__________________")
    print("Thread #" + str(credentials_index))
    print("done drawing image to r/place")
    print("__________________")
    break
```

You would have to test this out. If it does work, feel free to make a pull request and add a boolean to draw either horizontally (current code) or vertically.

**Comment by rdeepak2002** [comment]
Closing issue due to problem being solved.
