### ISSUE TITLE
Too many values to unpack

### ISSUE THREAD

**Issue by tattan** [rdeepak2002/reddit-place-script-2022#16]
There's an (r, g, b, a) value attempting to be unpacked into r, g, b. Error is in line on of closest_color. I have the same exact package versions as the requirements.txt for stuff so I'm not sure what's up here

**Comment by tattan** [comment]
Note I am running windows with python 3.10.4

**Comment by rdeepak2002** [comment]
Oh hm I am running the MacOS version of Python 3.10. Is your input image a .jpg image with no transparency? I have not added supported to .png files.

**Comment by tattan** [comment]
Yes I'm using a .jpg which don't support transparency. More than that the Pillow definition of the class doesn't even mention rgba only rgb so I'm stumped

**Comment by rdeepak2002** [comment]
Yeah I'm sorry. I am unsure how to debug this issue since I am on a different operating system and not experiencing the same issue.

If you figure out a solution to this, feel free to make a pull request so the script can also work for Windows users. 

Also did you try running the script with the image I provided in the repo? Does the same issue appear?

**Comment by tattan** [comment]
I will try with the image you gave (can't believe I haven't yet)

**Comment by tattan** [comment]
It's a problem with my image. 😢

**Comment by rdeepak2002** [comment]
Oh I see.
