### ISSUE TITLE
Print on same line

### ISSUE THREAD

**Issue by omar2205** [rdeepak2002/reddit-place-script-2022#25]
Maybe use `end="\r"` when printing to print on the same line.

**Comment by Randomblock1** [comment]
This might work if we start using curses, but since we have multiple newlines and multiple threads all outputting at different times, we can't add this now, as it is.

It would be quite nice to have, though.

See [this StackOverflow](https://stackoverflow.com/questions/35856818/how-to-edit-console-output) for someone with this exact problem.

**Comment by JAKONL** [comment]
Is this still relevant with the new logging system in place? @omar2205 & @Randomblock1

**Comment by ixi2101** [comment]
I vote to close

**Comment by omar2205** [comment]
@JAKONL didn't change what I was asking, but it's not a problem.

My thinking was, that each task has a line to print on, and the numbers get updated on the same line, without filling the console with random strings.

But, nvm.

**Comment by JAKONL** [comment]
That would be neat, a line on the terminal dedicated to each thread and those lines update with `XXX seconds remain`, `writing COLOR to coordinates xxx, xxx`, `successfully wrote COLOR to coordinates xxx, xxx`, and other types of messages by replacing what was previously on the line. I'm not super familiar with how to accomplish that and it sounds like quite the undertaking. If you're volunteering to implement I'd be happy to review.

**Comment by omar2205** [comment]
I wouldn't know how to achieve it with different threads.

But, we could use this https://github.com/bczsalba/pytermgui 
and on each thread creation, we assign a line from the bottom and `print_to` that line
